[package]
name = "piwfs"
version = "0.2.1"
authors = ["Ashymad <szymon.mikulicz@posteo.net>"]
edition = "2018"

[dependencies]
clap = "2"
hound = "3"
signal-hook = "0"
alsa = "0"
nix = "0.15"
indicator = {path = "./indicator"}
