[package]
name = "piwfs"
version = "0.1.0"
authors = ["Ashymad <szymon.mikulicz@posteo.net>"]
edition = "2018"

[dependencies]
rppal = "0.10"
docopt = "1"
serde = "1.0"
serde_derive = "1.0"
timer = "0.2.0"
chrono = "0.4.6"
alsa = "0.2.1"
libc = "0.2"
